### ISSUE TITLE
Update to v3

### ISSUE THREAD

**Issue by ghost** [nnnlog/nlog.dev#1]
## TODO
* [ ] new domain
* [ ] support blog (maybe?)
* change layout
     * [ ] design prototype
     * [ ] frontend with vue.js
* backend (when support blog)
    * [ ] Node.js (express)
    * [ ] MongoDB
